server:
  port: 8082



spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movieDB?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto: 'create-drop'